name: base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - awscli
  - autopep8
  - beautifulsoup4
  - black
  - boto3
  - click
  - cookiecutter
  - docformatter
  - flake8
  - html5lib
  - lxml
  - make
  - mamba
  - matplotlib
  - mysqlclient
  - notebook
  - numpy
  - openpyxl
  - pandas>=1.0
  - pip>=20
  - pre-commit
  - pymysql
  - pytest
  - pytest-cov
  - python=3.8
  - scipy
  - seaborn
  - sphinx
  - sphinx-autodoc-typehints
  - tabulate
  - tqdm
  - typeguard
  - urllib3
  - vulture
  - xlrd
  - pip:  # move packages failing on arm64/miniforge3 to pip
    - asciinema
    - jupyter_contrib_nbextensions
    - jupyter_nbextensions_configurator
    - ipython
    - ipywidgets
    - jupyter
    - jupyterlab
    - jupyterthemes
    - memory-profiler
    - rise

