name: base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - asciinema
  - awscli
  - autopep8
  - beautifulsoup4
  - black
  - boto3
  - click
  - cookiecutter
  - flake8
  - ipython
  - ipywidgets
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jupyterlab
  - jupyterthemes
  - lxml
  - make
  - matplotlib
  - mysqlclient
  - notebook
  - numpy
  - openpyxl
  - pandas>=1.0
  - pip>=20
  - pymysql
  - pytest
  - pytest-cov
  - python=3.8
  - rise
  - scipy
  - seaborn
  - sphinx
  - sphinx-autodoc-typehints
  - tabulate
  - tqdm
  - typeguard
  - urllib3
  - vulture
  - xlrd
